<?php

return [
    [
        "category_id" => 1,
        "restaurant_id" => 1,
        "name" => "Double cheeseburger",
        "description" => "Golosità compatta. Compatto, semplice ma unico. Per la merenda o un pranzo più light, gusto assicurato!",
        "ingredients" => "Doppio hamburger, formaggio cheddar, bacon croccante, cetriolini, pomodoro, ketchup e senape",
        "image" => "https://images.unsplash.com/photo-1534790566855-4cb788d389ec?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        "price" => 6.20,
    ],
    [
        "category_id" => 2,
        "restaurant_id" => 1,
        "name" => "Patatine fritte",
        "description" => "Dorate e croccanti patatine fritte",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1025&q=80",
        "price" => 3.80,
    ],
    [
        "category_id" => 3,
        "restaurant_id" => 1,
        "name" => "Coca Cola 45cl",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => 3.80,
    ],
    [
        "category_id" => 4,
        "restaurant_id" => 2,
        "name" => "Involtini primavera",
        "description" => "4 pezzi - vegetariano",
        "ingredients" => "Croccante sfoglia di farina di grano con ripieno di verdure",
        "image" => "https://images.unsplash.com/photo-1606525437679-037aca74a3e9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        "price" => 3.20,
    ],
    [
        "category_id" => 5,
        "restaurant_id" => 2,
        "name" => "Pollo al curry",
        "description" => "",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=684&q=80",
        "price" => 6.00,
    ],
    [
        "category_id" => 6,
        "restaurant_id" => 2,
        "name" => "Heineken 66cl",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => 4.00,
    ],
    [
        "category_id" => 7,
        "restaurant_id" => 3,
        "name" => "Alette di pollo speziate",
        "description" => "",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1608039755401-742074f0548d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80",
        "price" => 8.50,
    ],
    [
        "category_id" => 8,
        "restaurant_id" => 3,
        "name" => "Paella ai frutti di mare",
        "description" => "",
        "ingredients" => "Gamberetti , vongole , cozze senza Guccio , anelli di totano , cubi di astici",
        "image" => "https://images.unsplash.com/photo-1534080564583-6be75777b70a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        "price" => 15.00,
    ],
    [
        "category_id" => 9,
        "restaurant_id" => 3,
        "name" => "Fanta 1,5lt",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => 4.00,
    ],
    [
        "category_id" => 10,
        "restaurant_id" => 4,
        "name" => "Burger French Taco Small",
        "description" => "",
        "ingredients" => "Hamburger, patatine fritte, insalata e salsa di pomodoro",
        "image" => "https://images.unsplash.com/photo-1613514785940-daed07799d9b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        "price" => 7.00,
    ],
    [
        "category_id" => 11,
        "restaurant_id" => 4,
        "name" => "Churros - 3 pezzi",
        "description" => "",
        "ingredients" => "Anelli di pastella dolce, fritti e ricoperti di zucchero",
        "image" => "https://images.unsplash.com/photo-1624371414361-e670edf4898d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        "price" => 3.00,
    ],
    [
        "category_id" => 12,
        "restaurant_id" => 4,
        "name" => "Fuzetea alla Pesca 33cl",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => 3.00,
    ],
    [
        "category_id" => 13,
        "restaurant_id" => 5,
        "name" => "Pizza margherita",
        "description" => "",
        "ingredients" => "Pomodoro e mozzarella",
        "image" => "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        "price" => 6.00,
    ],
    [
        "category_id" => 14,
        "restaurant_id" => 5,
        "name" => "Nuggets di pollo",
        "description" => "10 pezzi",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1607329367978-0a651fdd8edb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1189&q=80",
        "price" => 4.50,
    ],
    [
        "category_id" => 15,
        "restaurant_id" => 5,
        "name" => "Sprite 33cl",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => 3.50,
    ],
];