<?php

return [
    [
        "restaurant_id" => "1",
        "name" => "Pizza margherita",
        "description" => "",
        "ingredients" => "Pomodoro, mozzarella e basilico fresco",
        "image" => "https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        "price" => "6.00",
    ],
    [
        "restaurant_id" => "1",
        "name" => "Patatine fritte",
        "description" => "",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1025&q=80",
        "price" => "4.00",
    ],
    [
        "restaurant_id" => "1",
        "name" => "Coca Cola 33cl",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => "3.50",
    ],
    [
        "restaurant_id" => "2",
        "name" => "Panino primaverile",
        "description" => "",
        "ingredients" => "Mozzarella di bufala, pomodoro e insalata",
        "image" => "",
        "price" => "6.00",
    ],
    [
        "restaurant_id" => "2",
        "name" => "Tagliere del ducato",
        "description" => "",
        "ingredients" => "Prosciutto crudo, coppa, salame, parmigiano reggiano, crostini e focaccia",
        "image" => "",
        "price" => "16.00",
    ],
    [
        "restaurant_id" => "2",
        "name" => "Birra Menabrea 66cl",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => "4.50",
    ],
    [
        "restaurant_id" => "3",
        "name" => "Polpo con patate",
        "description" => "Porzione da 300g",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1594973338928-5514e8cbb557?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        "price" => "11.70",
    ],
    [
        "restaurant_id" => "3",
        "name" => "Paella ai frutti di mare",
        "description" => "Porzione da 500g",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1534080564583-6be75777b70a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        "price" => "9.50",
    ],
    [
        "restaurant_id" => "3",
        "name" => "Sangria Don Simon 150 cl",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => "3.50",
    ],
    [
        "restaurant_id" => "4",
        "name" => "Poke love",
        "description" => "",
        "ingredients" => "Riso nero, salmone crudo , tonno crudo, pomodorini, edamame, avocado, mango, wakame, sesamo e salsa ponzu",
        "image" => "https://images.unsplash.com/photo-1604259597308-5321e8e4789c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1102&q=80",
        "price" => "12.50",
    ],
    [
        "restaurant_id" => "4",
        "name" => "Macedonia",
        "description" => "",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1519996529931-28324d5a630e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
        "price" => "3.00",
    ],
    [
        "restaurant_id" => "4",
        "name" => "Fuzetea Pesca",
        "description" => "40 cl",
        "ingredients" => "",
        "image" => "",
        "price" => "3.50",
    ],
    [
        "restaurant_id" => "5",
        "name" => "Cosce di pollo al forno",
        "description" => "",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
        "price" => "3.00",
    ],
    [
        "restaurant_id" => "5",
        "name" => "Nuggets di pollo",
        "description" => "6 pezzi",
        "ingredients" => "",
        "image" => "https://images.unsplash.com/photo-1607329367978-0a651fdd8edb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1189&q=80",
        "price" => "4.00",
    ],
    [
        "restaurant_id" => "5",
        "name" => "Sprite 33cl",
        "description" => "",
        "ingredients" => "",
        "image" => "",
        "price" => "1.50",
    ],
];