<?php

return [
    [
        "category_id" => 1,
        "restaurant_id" => 1,
        "name" => "Double cheeseburger",
        "description" => "Golosità compatta. Compatto, semplice ma unico. Per la merenda o un pranzo più light, gusto assicurato!",
        "ingredients" => "Doppio hamburger, formaggio cheddar, bacon croccante, cetriolini, pomodoro, ketchup e senape",
        "image" => "uploads/doublecheeseburger.avif",
        "price" => 6.20,
    ],
    [
        "category_id" => 1,
        "restaurant_id" => 1,
        "name" => "Whopper",
        "description" => "Doppio strato di hamburger, doppio strato di felicità!",
        "ingredients" => "Doppio hamburger, formaggio cheddar, bacon croccante, cetriolini, pomodoro, ketchup e senape",
        "image" => "uploads/bk-whopper.avif",
        "price" => 7.20,
    ],
    [
        "category_id" => 1,
        "restaurant_id" => 1,
        "name" => "Crispy chicken",
        "description" => "Nuovo panino con pollo super croccante!",
        "ingredients" => "Pollo fritto, formaggio, bacon, insalata",
        "image" => "uploads/bk-chicken.webp",
        "price" => 5.80,
    ],
    [
        "category_id" => 2,
        "restaurant_id" => 1,
        "name" => "Patatine fritte",
        "description" => "Dorate e croccanti patatine fritte",
        "ingredients" => "",
        "image" => "uploads/bk-fries.avif",
        "price" => 3.80,
    ],
    [
        "category_id" => 2,
        "restaurant_id" => 1,
        "name" => "Chicken nuggets",
        "description" => "Sfiziosissimi nuggets di pollo croccante",
        "ingredients" => "",
        "image" => "uploads/bk-nuggets.png",
        "price" => 4.50,
    ],
    [
        "category_id" => 3,
        "restaurant_id" => 1,
        "name" => "Coca Cola 45cl",
        "description" => "",
        "ingredients" => "",
        "image" => "uploads/bk-coca.jpg",
        "price" => 3.80,
    ],
    [
        "category_id" => 3,
        "restaurant_id" => 1,
        "name" => "Fanta 33cl",
        "description" => "",
        "ingredients" => "",
        "image" => "uploads/bk-fanta.jpg",
        "price" => 3.80,
    ],
    [
        "category_id" => 4,
        "restaurant_id" => 2,
        "name" => "Involtini primavera",
        "description" => "4 pezzi - vegetariano",
        "ingredients" => "Croccante sfoglia di farina di grano con ripieno di verdure",
        "image" => "uploads/involtini.avif",
        "price" => 3.20,
    ],
    [
        "category_id" => 4,
        "restaurant_id" => 2,
        "name" => "Ravioli al vapore",
        "description" => "6 pezzi - carne",
        "ingredients" => "Ravioli di carne con spezie cinesi al vapore",
        "image" => "uploads/cd-dumplings.jpg",
        "price" => 3.80,
    ],
    [
        "category_id" => 4,
        "restaurant_id" => 2,
        "name" => "Nuvole di drago",
        "description" => "Sfogliatine fritte ai gamberi",
        "ingredients" => "Farina, gamberi",
        "image" => "uploads/cd-nuvole.jpg",
        "price" => 2.50,
    ],
    [
        "category_id" => 5,
        "restaurant_id" => 2,
        "name" => "Pollo al curry",
        "description" => "",
        "ingredients" => "",
        "image" => "uploads/currychicken.avif",
        "price" => 6.50,
    ],
    [
        "category_id" => 5,
        "restaurant_id" => 2,
        "name" => "Riso alla cantonese",
        "description" => "Delizioso riso fritto con piselli e gamberi",
        "ingredients" => "Riso, uova, piselli, gamberi, cipolle",
        "image" => "uploads/cd-cantonese.jpg",
        "price" => 5.20,
    ],
    [
        "category_id" => 6,
        "restaurant_id" => 2,
        "name" => "Heineken 66cl",
        "description" => "",
        "ingredients" => "",
        "image" => "uploads/cd-heineken.webp",
        "price" => 4.00,
    ],
    [
        "category_id" => 6,
        "restaurant_id" => 2,
        "name" => "Sake Honjozo",
        "description" => "Delicatissimo saké di prugne",
        "ingredients" => "",
        "image" => "uploads/cd-sake.png",
        "price" => 7.50,
    ],
    [
        "category_id" => 7,
        "restaurant_id" => 3,
        "name" => "Alette di pollo speziate",
        "description" => "Alette speziate super piccanti, per i palati più forti",
        "ingredients" => "Pollo, peperoncini, ananas",
        "image" => "uploads/alette-speziate.avif",
        "price" => 8.50,
    ],
    [
        "category_id" => 7,
        "restaurant_id" => 3,
        "name" => "Picanha alla brace",
        "description" => "Squisita carne brasiliana alla brace",
        "ingredients" => "Carne di angus",
        "image" => "uploads/cf-picanha.jpg",
        "price" => 12.50,
    ],
    [
        "category_id" => 8,
        "restaurant_id" => 3,
        "name" => "Paella ai frutti di mare",
        "description" => "",
        "ingredients" => "Gamberetti , vongole , cozze senza Guccio , anelli di totano , cubi di astici",
        "image" => "uploads/paella.avif",
        "price" => 15.00,
    ],
    [
        "category_id" => 8,
        "restaurant_id" => 3,
        "name" => "Moqueca di Bahia",
        "description" => "Gustosissimo cocktail di gamberetti fritti",
        "ingredients" => "Gamberetti, panna, pomodori",
        "image" => "uploads/cf-moqueca.jpg",
        "price" => 11.50,
    ],
    [
        "category_id" => 8,
        "restaurant_id" => 3,
        "name" => "Platano fritto",
        "description" => "Deliziosi platani freschissimi fritti",
        "ingredients" => "",
        "image" => "uploads/cf-platano.jpg",
        "price" => 6.00,
    ],
    [
        "category_id" => 9,
        "restaurant_id" => 3,
        "name" => "Fanta 1,5lt",
        "description" => "",
        "ingredients" => "",
        "image" => "uploads/bk-fanta.jpg",
        "price" => 4.00,
    ],
    [
        "category_id" => 9,
        "restaurant_id" => 3,
        "name" => "Pinha Colada",
        "description" => "Freschissimo cocktail tropicale",
        "ingredients" => "",
        "image" => "uploads/cf-pinacolada.jpg",
        "price" => 7.00,
    ],
    [
        "category_id" => 10,
        "restaurant_id" => 4,
        "name" => "Chili barbacoa taco",
        "description" => "Spicy taco con barbacoa marinato",
        "ingredients" => "Manzo, pomodoro, lime, cipolle, peperoncini",
        "image" => "uploads/tb-taco.avif",
        "price" => 7.00,
    ],
    [
        "category_id" => 10,
        "restaurant_id" => 4,
        "name" => "Chicken Taco",
        "description" => "Croccante taco con pollo fritto",
        "ingredients" => "Pollo, panna acida, lime, coriandolo",
        "image" => "uploads/tb-chicken-taco.jpg",
        "price" => 7.00,
    ],
    [
        "category_id" => 10,
        "restaurant_id" => 4,
        "name" => "Fajitas Burrito",
        "description" => "Burrito tex-mex, buono anche a colazione!",
        "ingredients" => "Suino, pomodoro, formaggio, cipolle",
        "image" => "uploads/tb-fajitas-burrito.jpg",
        "price" => 8.50,
    ],
    [
        "category_id" => 11,
        "restaurant_id" => 4,
        "name" => "Churros - 3 pezzi",
        "description" => "",
        "ingredients" => "Stick di pastella dolce, fritti e ricoperti di zucchero",
        "image" => "uploads/tb-churros.avif",
        "price" => 3.00,
    ],
    [
        "category_id" => 12,
        "restaurant_id" => 4,
        "name" => "Fuzetea alla Pesca 33cl",
        "description" => "Rifrescante fuezeta al sapore di pesca",
        "ingredients" => "",
        "image" => "uploads/tb-fuezeta.jpeg",
        "price" => 3.00,
    ],
    [
        "category_id" => 12,
        "restaurant_id" => 4,
        "name" => "Coca cola 45cl",
        "description" => "",
        "ingredients" => "",
        "image" => "uploads/bk-coca.jpg",
        "price" => 3.50,
    ],
    [
        "category_id" => 13,
        "restaurant_id" => 5,
        "name" => "Pizza margherita",
        "description" => "",
        "ingredients" => "Pomodoro e mozzarella",
        "image" => "uploads/pg-margherita.avif",
        "price" => 6.00,
    ],
    [
        "category_id" => 14,
        "restaurant_id" => 5,
        "name" => "Pizza marinara",
        "description" => "",
        "ingredients" => "Pomodoro, basilico, aglio",
        "image" => "uploads/pg-marinara.webp",
        "price" => 4.50,
    ],
    [
        "category_id" => 14,
        "restaurant_id" => 5,
        "name" => "Pizza hawaiiana",
        "description" => "",
        "ingredients" => "Pomodoro, ananas, prosciutto cotto",
        "image" => "uploads/pg-ananas.jpg",
        "price" => 7.00,
    ],
    [
        "category_id" => 14,
        "restaurant_id" => 5,
        "name" => "Pizza bismark",
        "description" => "",
        "ingredients" => "Panna, speck, uovo, olio",
        "image" => "uploads/pg-bismark.jpg",
        "price" => 8.50,
    ],
    [
        "category_id" => 14,
        "restaurant_id" => 5,
        "name" => "Pizza quattro stagioni",
        "description" => "",
        "ingredients" => "Pomodoro, mozzarella, olive, carciofi, funghi, prosciutto cotto",
        "image" => "uploads/pg-quattro.jpg",
        "price" => 6.50,
    ],
    [
        "category_id" => 14,
        "restaurant_id" => 5,
        "name" => "Pizza tonno e cipolle",
        "description" => "",
        "ingredients" => "Pomodoro, mozzarella, tonno, cipolle",
        "image" => "uploads/pg-tonno.webp",
        "price" => 6.00,
    ],
    [
        "category_id" => 15,
        "restaurant_id" => 5,
        "name" => "Sprite 33cl",
        "description" => "",
        "ingredients" => "",
        "image" => "uploads/pg-sprite.png",
        "price" => 3.50,
    ],
    [
        "category_id" => 16,
        "restaurant_id" => 6,
        "name" => "Kebab di agnello",
        "description" => "",
        "ingredients" => "Agnello, ketchup, salsa yogurt, cipolle, pomodori",
        "image" => "uploads/rk-agnello.jpg",
        "price" => 6.50,
    ],
    [
        "category_id" => 17,
        "restaurant_id" => 6,
        "name" => "Chicken Shawarma",
        "description" => "",
        "ingredients" => "Pollo, coriandolo, pomodori, salsa yogurt",
        "image" => "uploads/rk-shwarma.jpg",
        "price" => 6.00,
    ],
    [
        "category_id" => 18,
        "restaurant_id" => 6,
        "name" => "Beef Shawarma",
        "description" => "",
        "ingredients" => "Manzo, coriandolo, pomodori, salsa yogurt",
        "image" => "uploads/rk-beef-shwarma.jpg",
        "price" => 7.50,
    ],
    [
        "category_id" => 18,
        "restaurant_id" => 6,
        "name" => "Pizza kebab",
        "description" => "",
        "ingredients" => "Pomodoro, mozzarella, manzo, cipolle, pomodori",
        "image" => "uploads/rk-pizza-kebab.jpg",
        "price" => 9.50,
    ],
    [
        "category_id" => 18,
        "restaurant_id" => 6,
        "name" => "Falafel",
        "description" => "Deliziosi spuntini a base di farina di ceci",
        "ingredients" => "Farina di ceci, spezie",
        "image" => "uploads/rk-falafel.jpeg",
        "price" => 3.50,
    ],
    [
        "category_id" => 18,
        "restaurant_id" => 6,
        "name" => "Baklava",
        "description" => "Dolcetti al miele e cannella",
        "ingredients" => "Pasta sfoglia, miele, cannella",
        "image" => "uploads/rk-baklava.jpeg",
        "price" => 4.50,
    ],
    [
        "category_id" => 19,
        "restaurant_id" => 7,
        "name" => "Poke al tonno",
        "description" => "",
        "ingredients" => "Riso, tonno, soia, sesamo",
        "image" => "uploads/pp-tuna.jpg",
        "price" => 12.50,
    ],
    [
        "category_id" => 19,
        "restaurant_id" => 7,
        "name" => "Poke al salmone",
        "description" => "",
        "ingredients" => "Salmone, avocado, edamame, cavolo, cetrioli",
        "image" => "uploads/pp-salmon.jpg",
        "price" => 11.50,
    ],
    [
        "category_id" => 19,
        "restaurant_id" => 7,
        "name" => "Poke con manzo",
        "description" => "",
        "ingredients" => "Manzo, carote, avocado, edamame, ravanelli",
        "image" => "uploads/pp-steak.jpg",
        "price" => 9.50,
    ],
    [
        "category_id" => 19,
        "restaurant_id" => 7,
        "name" => "Poke con granchio",
        "description" => "",
        "ingredients" => "Granchio, carote, avocado, edamame, ravanelli",
        "image" => "uploads/pp-crab.jpg",
        "price" => 14.50,
    ],
    [
        "category_id" => 19,
        "restaurant_id" => 7,
        "name" => "Poke vegetariana",
        "description" => "",
        "ingredients" => "Barbabietola, carote, avocado, edamame, soia",
        "image" => "uploads/pp-veg.jpg",
        "price" => 10.50,
    ],
    [
        "category_id" => 19,
        "restaurant_id" => 7,
        "name" => "Spirulina spritz",
        "description" => "Freschissimo cocktail estivo",
        "ingredients" => "",
        "image" => "uploads/pp-drink.jpg",
        "price" => 6.00,
    ],
    [
        "category_id" => 22,
        "restaurant_id" => 8,
        "name" => "Piadina ai fagioli speziata",
        "description" => "",
        "ingredients" => "Fagioli, spezie",
        "image" => "uploads/pi-fagioli.jpg",
        "price" => 6.50,
    ],
    [
        "category_id" => 22,
        "restaurant_id" => 8,
        "name" => "Piadina sfogliata all'olio",
        "description" => "",
        "ingredients" => "Pomodori, prosciutto cotto",
        "image" => "uploads/pi-piadina-sfogliata.jpg",
        "price" => 6.00,
    ],
    [
        "category_id" => 22,
        "restaurant_id" => 8,
        "name" => "Piadina al bacon",
        "description" => "",
        "ingredients" => "Bacon, rucola, pomodori",
        "image" => "uploads/pi-bacon.webp",
        "price" => 7.50,
    ],
    [
        "category_id" => 22,
        "restaurant_id" => 8,
        "name" => "Piadina con stracchino",
        "description" => "",
        "ingredients" => "Stracchino, prosciutto cotto, rucola, pomodori",
        "image" => "uploads/pi-stracchino.jpg",
        "price" => 5.50,
    ],
    [
        "category_id" => 22,
        "restaurant_id" => 8,
        "name" => "Piadina con verdure grigliate",
        "description" => "",
        "ingredients" => "Stracchino, zucchine, melanzane, pomodori",
        "image" => "uploads/pi-grigliate.jpg",
        "price" => 6.00,
    ],
    [
        "category_id" => 22,
        "restaurant_id" => 8,
        "name" => "Acqua SanBenedetto",
        "description" => "Bottiglietta da 50 cl",
        "ingredients" => "",
        "image" => "uploads/pi-acqua.jpg",
        "price" => 6.00,
    ],
    [
        "category_id" => 25,
        "restaurant_id" => 9,
        "name" => "Pizza ai frutti di mare",
        "description" => "",
        "ingredients" => "Gamberi, muscoli",
        "image" => "uploads/penp-mare.webp",
        "price" => 13.50,
    ],
    [
        "category_id" => 25,
        "restaurant_id" => 9,
        "name" => "Pizza al caviale",
        "description" => "",
        "ingredients" => "Caviale, scaglie d'oro",
        "image" => "uploads/penp-caviar.jpg",
        "price" => 18.00,
    ],
    [
        "category_id" => 25,
        "restaurant_id" => 9,
        "name" => "Pizza ai porcini",
        "description" => "",
        "ingredients" => "Caviale, scaglie d'oro",
        "image" => "uploads/penp-porcini.avif",
        "price" => 16.00,
    ],
    [
        "category_id" => 25,
        "restaurant_id" => 9,
        "name" => "Pizza panna e speck",
        "description" => "",
        "ingredients" => "Panna, speck",
        "image" => "uploads/penp-panna.jpg",
        "price" => 9.50,
    ],
    [
        "category_id" => 25,
        "restaurant_id" => 9,
        "name" => "Cabernet Sauvignon",
        "description" => "Annata 2017",
        "ingredients" => "",
        "image" => "uploads/penp-cabernet.jpg",
        "price" => 25.00,
    ],
    [
        "category_id" => 25,
        "restaurant_id" => 9,
        "name" => "Chianti Classico",
        "description" => "Annata 2017",
        "ingredients" => "",
        "image" => "uploads/penp-chianti.jpg",
        "price" => 22.00,
    ],
    [
        "category_id" => 25,
        "restaurant_id" => 9,
        "name" => "Pinot Grigio Ramato",
        "description" => "Annata 2021",
        "ingredients" => "",
        "image" => "uploads/penp-pinot.jpg",
        "price" => 28.00,
    ],
    [
        "category_id" => 28,
        "restaurant_id" => 10,
        "name" => "Crema di zucca",
        "description" => "",
        "ingredients" => "Zucca, panna, pistacchi",
        "image" => "uploads/av-zucca.webp",
        "price" => 6.50,
    ],
    [
        "category_id" => 28,
        "restaurant_id" => 10,
        "name" => "Vellutata di asparagi",
        "description" => "",
        "ingredients" => "Asparagi, panna",
        "image" => "uploads/av-asparagi.jpg",
        "price" => 8.50,
    ],
    [
        "category_id" => 28,
        "restaurant_id" => 10,
        "name" => "Zuppa di cipolle",
        "description" => "",
        "ingredients" => "Cipolle, panna, aglio, formaggio",
        "image" => "uploads/av-cipolle.avif",
        "price" => 6.00,
    ],
    [
        "category_id" => 28,
        "restaurant_id" => 10,
        "name" => "Insalatona estiva",
        "description" => "",
        "ingredients" => "Feta, pomodorini, rucola, olio EVO",
        "image" => "uploads/av-feta.jpg",
        "price" => 7.50,
    ],
    [
        "category_id" => 28,
        "restaurant_id" => 10,
        "name" => "Ratatouille",
        "description" => "",
        "ingredients" => "Melanzane, peperoni, zucchine, pomodori",
        "image" => "uploads/av-rata.jpg",
        "price" => 5.50,
    ],
    [
        "category_id" => 28,
        "restaurant_id" => 10,
        "name" => "Polpette di miglio",
        "description" => "",
        "ingredients" => "Miglio decorticato, spezie, piselli",
        "image" => "uploads/av-miglio.jpg",
        "price" => 5.50,
    ],
    [
        "category_id" => 28,
        "restaurant_id" => 10,
        "name" => "Poke vegetariano",
        "description" => "",
        "ingredients" => "Tofu, avocado, carote, quinoa",
        "image" => "uploads/av-poke.jpg",
        "price" => 5.50,
    ],
];