<?php

return [
        [
            'user_id'=>'1',
            'name'=>'Burger King',
            'slug'=>'burger-king',
            'vat_number'=>'12453334154',
            'address'=>'Via Aristide Merloni, 141',
            'postal_code'=>'00155',
            'city'=>'Roma',
            'business_times'=>'11AM to 10PM',
            'phone_number'=>'06 87165 100',
            'delivery_cost'=>3.50,
            'min_purchase'=>6.99,
            'image'=>'https://logowik.com/content/uploads/images/310_burgerking.jpg',
        ],
        [
            'user_id'=>'2',
            'name'=>'Chinese Dragon',
            'slug'=>'chinese-dragon',
            'vat_number'=>'12453334254',
            'address'=>'Piazzale Appio, 2',
            'postal_code'=>'00184',
            'city'=>'Roma',
            'business_times'=>'11AM to 8PM',
            'phone_number'=>'06 87165 200',
            'delivery_cost'=>8.50,
            'min_purchase'=>33.24,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2HelRJBEmm4ZmxzrGPzDrU8mYRXfTU2qK7w&usqp=CAU',
        ],
        [
            'user_id'=>'3',
            'name'=>'The Crazy Flamingo',
            'slug'=>'the-crazy-flamingo',
            'vat_number'=>'83640157354',
            'address'=>'Via Casellina, 1519',
            'postal_code'=>'00136',
            'city'=>'Roma',
            'business_times'=>'5PM to 12AM',
            'phone_number'=>'06 87165 300',
            'delivery_cost'=>2.50,
            'min_purchase'=>40.00,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfr-otupqKfVZaes3bB9fDh4enrpHWmMEIVA&usqp=CAU',
        ],
        [
            'user_id'=>'4',
            'name'=>'Taco Bell',
            'slug'=>'taco-bell',
            'vat_number'=>'12453543344',
            'address'=>'Corso Vittorio Emanuele, 254',
            'postal_code'=>'00186',
            'city'=>'Roma',
            'business_times'=>'3PM to 12AM',
            'phone_number'=>'06 87165 400',
            'delivery_cost'=>1.50,
            'min_purchase'=>5.50,
            'image'=>'https://a.mktgcdn.com/p/OnusxQjxa5ZL-z9Fp4_jLLkMKa2Bg1B-lqEe09Lb3Uc/1398x786.jpg',
        ],
        [
            'user_id'=>'5',
            'name'=>'Pizzeria da Giggino',
            'slug'=>'pizzeria-da-diggino',
            'vat_number'=>'12453543345',
            'address'=>'Vicolo della Renella, 94',
            'postal_code'=>'00153',
            'city'=>'Roma',
            'business_times'=>'12PM to 10AM',
            'phone_number'=>'06 87165 500',
            'delivery_cost'=>1.50,
            'min_purchase'=>5.50,
            'image'=>'https://img.freepik.com/premium-vector/pizza-logo-design-template_15146-192.jpg?w=2000',
        ],
        [
            'user_id'=>'6',
            'name'=>'Rashad Ali Kebab',
            'slug'=>'rashad-ali-kebab',
            'vat_number'=>'12453543346',
            'address'=>'Via della Renella, 94',
            'postal_code'=>'00163',
            'city'=>'Roma',
            'business_times'=>'12PM to 10AM',
            'phone_number'=>'06 87165 506',
            'delivery_cost'=>1.50,
            'min_purchase'=>5.50,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqVYlhXNJ3v4EcGOmDhu0NMjBqvUpIQJY0ng&usqp=CAU',
        ],
        [
            'user_id'=>'7',
            'name'=>'Pokeito',
            'slug'=>'pokeito',
            'vat_number'=>'12453543347',
            'address'=>'Via Roma, 96',
            'postal_code'=>'00173',
            'city'=>'Roma',
            'business_times'=>'12PM to 10AM',
            'phone_number'=>'06 87165 507',
            'delivery_cost'=>3.50,
            'min_purchase'=>2.50,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8s0Y4QAgC9DoZhuLeL7gJd7NkZoOKoWNCZg&usqp=CAU',
        ],
        [
            'user_id'=>'8',
            'name'=>'Pokeito',
            'slug'=>'pokeito',
            'vat_number'=>'12453543348',
            'address'=>'Piazza del Gozzometro, 1',
            'postal_code'=>'00188',
            'city'=>'Roma',
            'business_times'=>'12PM to 10AM',
            'phone_number'=>'06 87165 508',
            'delivery_cost'=>3.50,
            'min_purchase'=>2.50,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRur-9VUxPbfUzj5TRgpIV0F1kcs9Lz9SgU9A&usqp=CAU',
        ],
        [
            'user_id'=>'9',
            'name'=>'Penguin',
            'slug'=>'penguin',
            'vat_number'=>'12453543349',
            'address'=>'Piazza del Gozzometro, 5',
            'postal_code'=>'00189',
            'city'=>'Roma',
            'business_times'=>'12PM to 10AM',
            'phone_number'=>'06 87165 509',
            'delivery_cost'=>3.50,
            'min_purchase'=>0,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT861pNaPx4DKdGNj2a0Nai3vPxvCXx3ECOTg&usqp=CAU',
        ],
        [
            'user_id'=>'9',
            'name'=>'Aloe Vera',
            'slug'=>'aloe-vera',
            'vat_number'=>'22453543340',
            'address'=>'Via del Gozzometro, 5',
            'postal_code'=>'10186',
            'city'=>'Roma',
            'business_times'=>'12PM to 10AM',
            'phone_number'=>'07 87165 509',
            'delivery_cost'=>3.50,
            'min_purchase'=>5.00,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf8jRXn1huDwhQwqg1MMgE39WiNq1ooVsrwA&usqp=CAU',
        ],
];

