<?php

return [
    [
        'user_id' => '1',
        'name' => 'Burger King',
        'slug' => 'burger-king',
        'vat_number' => '12453334154',
        'address' => 'Via Aristide Merloni, 141',
        'postal_code' => '00155',
        'city' => 'Roma',
        'business_times' => '20:00',
        'phone_number' => '06 87165 100',
        'delivery_cost' => 3.50,
        'min_purchase' => 6.99,
        'typologies_id' => [
            3,
            7,
        ],
        'image' => 'uploads/burgerking.jpg',
    ],
    [
        'user_id' => '2',
        'name' => 'Chinese Dragon',
        'slug' => 'chinese-dragon',
        'vat_number' => '12453334254',
        'address' => 'Piazzale Appio, 2',
        'postal_code' => '00184',
        'city' => 'Roma',
        'business_times' => '20:00',
        'phone_number' => '06 87165 200',
        'delivery_cost' => 8.50,
        'min_purchase' => 33.24,
        'typologies_id' => [
            5,
            7,
        ],
        'image' => 'uploads/dragons.png',
    ],
    [
        'user_id' => '3',
        'name' => 'The Crazy Flamingo',
        'slug' => 'the-crazy-flamingo',
        'vat_number' => '83640157354',
        'address' => 'Via Casellina, 1519',
        'postal_code' => '00136',
        'city' => 'Roma',
        'business_times' => '12:00',
        'phone_number' => '06 87165 300',
        'delivery_cost' => 2.50,
        'min_purchase' => 40.00,
        'typologies_id' => [
            5,
            6,
            7,
        ],
        'image' => 'uploads/crazyflamingo.png',
    ],
    [
        'user_id' => '4',
        'name' => 'Taco Bell',
        'slug' => 'taco-bell',
        'vat_number' => '12453543344',
        'address' => 'Corso Vittorio Emanuele, 254',
        'postal_code' => '00186',
        'city' => 'Roma',
        'business_times' => '12:00',
        'phone_number' => '06 87165 400',
        'delivery_cost' => 1.50,
        'min_purchase' => 5.50,
        'typologies_id' => [
            3,
            6,
            7,
        ],
        'image' => 'uploads/tacobell.jpg',
    ],
    [
        'user_id' => '5',
        'name' => 'Pizzeria da Giggino',
        'slug' => 'pizzeria-da-diggino',
        'vat_number' => '12453543345',
        'address' => 'Vicolo della Renella, 94',
        'postal_code' => '00153',
        'city' => 'Roma',
        'business_times' => '10:00',
        'phone_number' => '06 87165 500',
        'delivery_cost' => 1.50,
        'min_purchase' => 5.50,
        'typologies_id' => [
            1,
            4,
        ],
        'image' => 'uploads/pizzeriagigino.avif',
    ],
    [
        'user_id' => '6',
        'name' => 'Rashad Ali Kebab',
        'slug' => 'rashad-ali-kebab',
        'vat_number' => '12453543346',
        'address' => 'Via della Renella, 94',
        'postal_code' => '00163',
        'city' => 'Roma',
        'business_times' => '10:00',
        'phone_number' => '06 87165 506',
        'delivery_cost' => 1.50,
        'min_purchase' => 5.50,
        'typologies_id' => [
            1,
            2,
            6,
        ],
        'image' => 'uploads/rashadkebab.jpeg',
    ],
    [
        'user_id' => '7',
        'name' => 'Pokeito',
        'slug' => 'pokeito',
        'vat_number' => '12453543347',
        'address' => 'Via Roma, 96',
        'postal_code' => '00173',
        'city' => 'Roma',
        'business_times' => '10:00',
        'phone_number' => '06 87165 507',
        'delivery_cost' => 3.50,
        'min_purchase' => 2.50,
        'typologies_id' => [
            5,
            7,
        ],
        'image' => 'uploads/pokeio.png',
    ],
    [
        'user_id' => '8',
        'name' => 'Piedine',
        'slug' => 'piedine',
        'vat_number' => '12453543348',
        'address' => 'Piazza del Gozzometro, 1',
        'postal_code' => '00188',
        'city' => 'Roma',
        'business_times' => '10:00',
        'phone_number' => '06 87165 508',
        'delivery_cost' => 3.50,
        'min_purchase' => 2.50,
        'typologies_id' => [
            4,
            6,
        ],
        'image' => 'uploads/piedine.jpeg',
    ],
    [
        'user_id' => '9',
        'name' => 'Pizza Penguin',
        'slug' => 'pizza-penguin',
        'vat_number' => '12453543349',
        'address' => 'Piazza del Gozzometro, 5',
        'postal_code' => '00189',
        'city' => 'Roma',
        'business_times' => '10:00',
        'phone_number' => '06 87165 509',
        'delivery_cost' => 3.50,
        'min_purchase' => 0,
        'typologies_id' => [
            1,
            4,
            6,
        ],
        'image' => 'uploads/pizzapenguin.jpeg',
    ],
    [
        'user_id' => '10',
        'name' => 'Aloe Vera',
        'slug' => 'aloe-vera',
        'vat_number' => '22453543340',
        'address' => 'Via del Gozzometro, 5',
        'postal_code' => '10186',
        'city' => 'Roma',
        'business_times' => '10:00',
        'phone_number' => '07 87165 509',
        'delivery_cost' => 3.50,
        'min_purchase' => 5.00,
        'typologies_id' => [
            4,
            5,
        ],
        'image' => 'uploads/aloevera.png',
    ],
];
