<?php

return [
        [
            'user_id'=>'1',
            'name'=>'Burger King',
            'slug'=>'burger-king',
            'vat_number'=>'124533341',
            'address'=>'Via Aristide Merloni, 141',
            'postal_code'=>'00155',
            'city'=>'Roma',
            'business_times'=>'11AM to 10PM',
            'phone_number'=>'06 87165 100',
            'delivery_cost'=>3.50,
            'min_purchase'=>6.99,
            'image'=>'https://logowik.com/content/uploads/images/310_burgerking.jpg',
        ],
        [
            'user_id'=>'2',
            'name'=>'Chinese Dragon',
            'slug'=>'chinese-dragon',
            'vat_number'=>'124533342',
            'address'=>'Piazzale Appio, 2',
            'postal_code'=>'00184',
            'city'=>'Roma',
            'business_times'=>'11AM to 8PM',
            'phone_number'=>'06 87165 200',
            'delivery_cost'=>8.50,
            'min_purchase'=>33.24,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2HelRJBEmm4ZmxzrGPzDrU8mYRXfTU2qK7w&usqp=CAU',
        ],
        [
            'user_id'=>'3',
            'name'=>'The Crazy Flamingo',
            'slug'=>'the-crazy-flamingo',
            'vat_number'=>'836401573',
            'address'=>'Via Casellina, 1519',
            'postal_code'=>'00136',
            'city'=>'Roma',
            'business_times'=>'5PM to 12AM',
            'phone_number'=>'06 87165 300',
            'delivery_cost'=>2.50,
            'min_purchase'=>40.00,
            'image'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfr-otupqKfVZaes3bB9fDh4enrpHWmMEIVA&usqp=CAU',
        ],
        [
            'user_id'=>'4',
            'name'=>'Taco Bell',
            'slug'=>'taco-bell',
            'vat_number'=>'124533344',
            'address'=>'Corso Vittorio Emanuele, 254',
            'postal_code'=>'00186',
            'city'=>'Roma',
            'business_times'=>'3PM to 12AM',
            'phone_number'=>'06 87165 400',
            'delivery_cost'=>1.50,
            'min_purchase'=>5.50,
            'image'=>'https://a.mktgcdn.com/p/OnusxQjxa5ZL-z9Fp4_jLLkMKa2Bg1B-lqEe09Lb3Uc/1398x786.jpg',
        ],
        [
            'user_id'=>'5',
            'name'=>'Pizzeria da Giggino',
            'slug'=>'pizzeria-da-giggino',
            'vat_number'=>'124533345',
            'address'=>'Vicolo della Renella, 94',
            'postal_code'=>'00153',
            'city'=>'Roma',
            'business_times'=>'12PM to 10AM',
            'phone_number'=>'06 87165 500',
            'delivery_cost'=>1.50,
            'min_purchase'=>5.50,
            'image'=>'https://img.freepik.com/premium-vector/pizza-logo-design-template_15146-192.jpg?w=2000',
        ],
];